version: '3.8'

services:

  catalog:
    image: bazar
    command: sh -c "node app.js && sleep infinity"
    volumes:
      - ./catalog:/home
      - catalog-data:/home/catalog
    networks:
      - net
    deploy:
      replicas: 2
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.type == worker

  order:
    image: bazar
    command: sh -c "node app.js && sleep infinity"
    volumes:
      - ./order:/home
      - order-data:/home/order
    networks:
      - net
    deploy:
      replicas: 2
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.type == worker


  front:
    image: bazar
    command: sh -c "node app.js && sleep infinity"
    volumes:
      - ./front:/home
    networks:
      - net
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.type == worker
    ports:
      - "4004:3000"

networks:
  net:

volumes:
  catalog-data:
  order-data:
